name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        namespace: [arce0406]
        image_name: [discord-bot]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create env file
        run: |
          touch .env
          echo DISCORD_TOKEN="${{ secrets.DISCORD_TOKEN }}" >> .env
          echo DISCORD_CLIENT_ID="${{ secrets.DISCORD_CLIENT_ID }}" >> .env
          echo NODE_OPTIONS="--enable-source-maps" >> .env
          cat .env

      - name: Build Docker image
        run: docker build -t ${{ matrix.namespace }}/${{ matrix.image_name }}:latest .

      - name: Push Docker image
        run: docker push ${{ matrix.namespace }}/${{ matrix.image_name }}:latest

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ matrix.namespace }}/${{ matrix.image_name }}:latest
